[package]
name = "ezsockets-chat-server-axum"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.52"
axum = "0.6.1"
ezsockets = { path = "../../", features = ["axum"] }
tokio = { version = "1.17.0", features = ["full"] }
tracing = "0.1.32"
tracing-subscriber = "0.3.9"
