[package]
name = "ezsockets-chat-client"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.52"
ezsockets = { path = "../../", features = ["client"] }
tokio = { version = "1.17.0", features = ["full"] }
tracing = "0.1.32"
tracing-subscriber = "0.3.9"
url = "2.2.2"
